Repository salesforce/p4-fusion, pull requests merged in 2022-05, with the labels that each got.

#25 main: Add warning for receiving an empty client spec due to mismatched P4PORT
  p4-fusion/main.cc
  p4-fusion/utils/arguments.cc
  p4-fusion/utils/arguments.h
Labels: enhancement

#26 main: Add version string
  p4-fusion/main.cc
Labels: enhancement

#29 Executable support
  p4-fusion/git_api.cc
  p4-fusion/git_api.h
  p4-fusion/main.cc
  p4-fusion/p4_api.cc
  p4-fusion/p4_api.h
  tests/tests.git.h
Labels: cla:signed

#30 git: Strip away the depot path from the beginning of the file path
  p4-fusion/git_api.cc
  p4-fusion/git_api.h
  p4-fusion/main.cc
  p4-fusion/utils/std_helpers.cc
  p4-fusion/utils/std_helpers.h
  tests/tests.common.h
  tests/tests.git.h
  tests/tests.utils.h
Labels: bug

#31 threadpool: Fix crash by p4 library shutdown before p4 contexts
  p4-fusion/thread_pool.cc
Labels: bug

#33 build: Add support for Helix Core C++ API version 2021.2
  README.md
  p4-fusion/CMakeLists.txt
Labels: enhancement
