Repository salesforce/p4-fusion, pull requests merged in 2022-03, with the labels that each got.

#11 p4: Improve text buffer handling to be less error prone, less likely to break
  p4-fusion/commands/print_result.cc
Labels: enhancement

#12 p4: Retrieve user full names if possible and use those while committing
  p4-fusion/commands/users_result.cc
  p4-fusion/commands/users_result.h
  p4-fusion/git_api.cc
  p4-fusion/main.cc
Labels: enhancement

#13 threadpool: Guard exceptions array behind a mutex
  p4-fusion/thread_pool.cc
  p4-fusion/thread_pool.h
Labels: bug

#15 p4: Fix .git file used by submodules
  p4-fusion/commands/change_list.cc
Labels: cla:signed

#17 all: Update license year
  LICENSE.txt
  license_headers.sh
  p4-fusion/commands/change_list.cc
  p4-fusion/commands/change_list.h
  p4-fusion/commands/changes_result.cc
  p4-fusion/commands/changes_result.h
  p4-fusion/commands/client_result.cc
  p4-fusion/commands/client_result.h
  p4-fusion/commands/describe_result.cc
  p4-fusion/commands/describe_result.h
  p4-fusion/commands/file_data.h
  p4-fusion/commands/files_result.cc
  p4-fusion/commands/files_result.h
  p4-fusion/commands/info_result.cc
  p4-fusion/commands/info_result.h
  p4-fusion/commands/print_result.cc
  p4-fusion/commands/print_result.h
  p4-fusion/commands/result.cc
  p4-fusion/commands/result.h
  p4-fusion/commands/sizes_result.cc
  p4-fusion/commands/sizes_result.h
  p4-fusion/commands/sync_result.cc
  p4-fusion/commands/sync_result.h
  p4-fusion/commands/users_result.cc
  p4-fusion/commands/users_result.h
  p4-fusion/common.h
  p4-fusion/git_api.cc
  p4-fusion/git_api.h
  p4-fusion/main.cc
  p4-fusion/p4_api.cc
  p4-fusion/p4_api.h
  p4-fusion/thread_pool.cc
  p4-fusion/thread_pool.h
  p4-fusion/utils/arguments.cc
  p4-fusion/utils/arguments.h
  p4-fusion/utils/std_helpers.cc
  p4-fusion/utils/std_helpers.h
  p4-fusion/utils/timer.cc
  p4-fusion/utils/timer.h
  tests/main.cc
  vendor/minitrace/minitrace.h
Labels: documentation, enhancement

#18 p4: Use std helpers for string comparisons
  p4-fusion/commands/change_list.cc
  p4-fusion/p4_api.cc
Labels: enhancement

#19 p4: Check if p4 object is a file and return early if it isn't
  p4-fusion/commands/describe_result.cc
Labels: cla:signed

#21 all: Improve logging and error handling
  README.md
  p4-fusion/commands/change_list.cc
  p4-fusion/commands/change_list.h
  p4-fusion/commands/changes_result.cc
  p4-fusion/commands/info_result.cc
  p4-fusion/commands/info_result.h
  p4-fusion/commands/users_result.cc
  p4-fusion/main.cc
  p4-fusion/p4_api.cc
  p4-fusion/p4_api.h
  p4-fusion/thread_pool.cc
  p4-fusion/utils/time_helpers.cc
  p4-fusion/utils/time_helpers.h
  tests/CMakeLists.txt
  tests/main.cc
  tests/tests.common.h
  tests/tests.git.h
  tests/tests.utils.h
Labels: bug, enhancement

#22 p4: Fix initialization mutex usage to properly allow only 1 init at a time
  p4-fusion/p4_api.cc
Labels: bug
